CREATE TABLE IF NOT EXISTS users (
	id SERIAL PRIMARY KEY,
	first_name VARCHAR(16) NOT NULL,
	phone_number VARCHAR(10) NOT NULL UNIQUE,
	email TEXT DEFAULT NULL UNIQUE,
	password_hash BYTEA NOT NULL,
	created_at TIMESTAMP DEFAULT NOW()
);