CREATE TABLE IF NOT EXISTS users (
	id SERIAL PRIMARY KEY,
	first_name VARCHAR(16) NOT NULL,
	phonenumber VARCHAR(10) NOT NULL UNIQUE,
	email TEXT NOT NULL UNIQUE,
	password BYTEA NOT NULL,
	created_at TIMESTAMP DEFAULT NOW()
);