env: local
database_url: "postgres://root:pw123@localhost:5432/ecom?sslmode=disable"
grpc:
  port: 3000
  timeout: 5s
postgres:
  max_conns: 30
  min_conns: 5
  max_conn_life_time: 1h
  max_conn_idle_time: 30m
  check_period: 1m
